eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@10.0.0.2:8761/eureka/
      
server:
  port: 8772
  
spring:
  application:
    name: ehotel-product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://10.0.0.4:3306/ehotel
    username: test
    password: test123